export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#00f0ff",
        "on-error": "#690005",
        "surface-container-lowest": "#0a0e15",
        "error-container": "#93000a",
        "primary-fixed": "#7df4ff",
        "inverse-on-surface": "#2d3038",
        "tertiary-fixed-dim": "#4edea3",
        "primary-fixed-dim": "#00dbe9",
        "tertiary": "#d8ffe7",
        "on-secondary-fixed": "#001d33",
        "error": "#ffb4ab",
        "surface-bright": "#353941",
        "secondary-fixed-dim": "#98cbff",
        "surface-dim": "#0f131b",
        "surface-container": "#1c2027",
        "on-secondary-container": "#003558",
        "on-primary": "#00363a",
        "on-secondary": "#003354",
        "background": "#0f131b",
        "tertiary-fixed": "#6ffbbe",
        "on-background": "#dfe2ed",
        "outline-variant": "#3b494b",
        "surface-container-high": "#262a32",
        "on-surface-variant": "#b9cacb",
        "surface": "#0f131b",
        "on-secondary-fixed-variant": "#004a77",
        "surface-tint": "#00dbe9",
        "inverse-surface": "#dfe2ed",
        "on-tertiary-container": "#006d4a",
        "on-primary-fixed-variant": "#004f54",
        "secondary": "#98cbff",
        "outline": "#849495",
        "surface-container-low": "#181c23",
        "primary": "#dbfcff",
        "secondary-container": "#00a2fd",
        "on-tertiary": "#003824",
        "on-primary-container": "#006970",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#31353d",
        "tertiary-container": "#65f2b5",
        "on-primary-fixed": "#002022",
        "secondary-fixed": "#cfe5ff",
        "on-tertiary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#002113",
        "surface-variant": "#31353d",
        "on-surface": "#dfe2ed",
        "inverse-primary": "#006970"
      }
    }
  }
};